import '../styles/globals.scss';
import type { Metadata } from 'next';
import { Toaster } from 'react-hot-toast';

import { Inter } from 'next/font/google';
import Script from 'next/script';

import ReduxProvider from '@/redux/ReduxProvider';

import TanStackProvider from '@/utils/TanStackProvider';

import { AuthProvider } from '@/context/AuthContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'PlayTrade MarketPlace',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
        <meta property="author" content="vladdonets" />
        <Script src="https://telegram.org/js/telegram-web-app.js" defer></Script>
      </head>
      <body className={inter.className}>
        <ReduxProvider>
          <AuthProvider>
            <TanStackProvider>
              <Toaster />
              {children}
            </TanStackProvider>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
